// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbW8G1GAkNx_rTX97NudxmndlzdG9Nk0s',
    appId: '1:485292322255:web:d0b2678c63382c5fad36ba',
    messagingSenderId: '485292322255',
    projectId: 'flutterchatapp-b0696',
    authDomain: 'flutterchatapp-b0696.firebaseapp.com',
    storageBucket: 'flutterchatapp-b0696.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChNzHLQ2H8_Xp1jIphBBpReh42dTDVgik',
    appId: '1:485292322255:android:a339eba38961163ead36ba',
    messagingSenderId: '485292322255',
    projectId: 'flutterchatapp-b0696',
    storageBucket: 'flutterchatapp-b0696.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLuM-7x52Boe4x8NV-C7vEvAPi1Xw52m4',
    appId: '1:485292322255:ios:df53d4cb2c6adaf7ad36ba',
    messagingSenderId: '485292322255',
    projectId: 'flutterchatapp-b0696',
    storageBucket: 'flutterchatapp-b0696.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLuM-7x52Boe4x8NV-C7vEvAPi1Xw52m4',
    appId: '1:485292322255:ios:df53d4cb2c6adaf7ad36ba',
    messagingSenderId: '485292322255',
    projectId: 'flutterchatapp-b0696',
    storageBucket: 'flutterchatapp-b0696.firebasestorage.app',
    iosBundleId: 'com.example.flutterChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbW8G1GAkNx_rTX97NudxmndlzdG9Nk0s',
    appId: '1:485292322255:web:0394df7d1387ea6fad36ba',
    messagingSenderId: '485292322255',
    projectId: 'flutterchatapp-b0696',
    authDomain: 'flutterchatapp-b0696.firebaseapp.com',
    storageBucket: 'flutterchatapp-b0696.firebasestorage.app',
  );
}
